import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layouts/Footer";
import Navbar from "@/components/layouts/Navbar";
import { CartProvider } from "../context/CartContext";
import { ConvexClientProvider } from "./ConvexClientProvider";
import CartModal from "@/components/layouts/CartModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {" "}
        {/* <ConvexClientProvider> */}
        <CartProvider>
          <Navbar />
          <CartModal /> 
          {children}
          <Footer />
        </CartProvider>
        {/* </ConvexClientProvider> */}
      </body>
    </html>
  );
}
